### ISSUE TITLE
Difficulty reading Apple II nib disk images

### ISSUE THREAD

**Issue by ryandesign** [TomHarte/CLK#1249]
Loading [Prince of Persia (rebuilt from source code) side A.nib](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/action/prince_of_persia/Prince%20of%20Persia%20%28rebuilt%20from%20source%20code%29%20side%20A.nib) in OpenEmulator or Virtual ][ only takes about 10 seconds from power-on to splash screen, but Clock Signal takes 60 seconds, if it makes it that far. Often, the game instead displays the message "Insert Prince of Persia Disk". After pressing any key some number of times, it eventually load successfully, but in attract mode the game cycles through many screens, occasionally needing to load from disk again, which may encounter the problem again.

Picking another nib disk image at random, I tried [Arcticfox.nib](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/action/Arcticfox.nib). In Virtual ][, it displays the splash screen within about 3 seconds and then finishes loading the game a few seconds later, but Clock Signal takes 40 seconds to show the splash screen, followed a few seconds later by "ERR".

**Comment by TomHarte** [comment]
NIBs are problematic for Clock Signal because they're a poor rendering of a source disk, omitting slip bits and therefore requiring a bunch of assumptions to be made to turn back into something approximating the intended flux pattern*.

As per the commentary `NIB::get_track_at_position`, Clock Signal's current approach is to look for sector prologues and walk backwards inserting slip bits into what it hopes is a preceding sync area. I guess in this case that's possibly not working correctly.

\* Some other emulators — though I can't speak as to OpenEmulator or Virtual ][ — are probably able to skip the whole controller emulation entirely, just shoving bytes from the file directly to the processor but that isn't really an option here.

**Comment by ryandesign** [comment]
Do you have examples of nib disk images that do work with Clock Signal? Maybe examining the differences between those and the ones I tried will shed light on what to change.

I'll read up on the nib format.

**Comment by TomHarte** [comment]
This is why I'm not a fan of NIBs; by not including slip bits the onus is on the tool to insert them, which puts it in an awkward ground somewhere between supporting non-standard formats and not.

Anyway, I guess my NIB-to-flux thing needs a fallback that looks for some other usable place to insert slip bits if standard prologues aren't found. Most likely any nonstandard format is still using a sequence of `FF`s so probably the task is easy. Otherwise I guess just cram in slip bits as frequently as possible up until you're approaching density limits.

And if it really, really matters to the protection scheme where the slip bits are then it isn't compatible with the NIB file format.

**Comment by ryandesign** [comment]
I'm currently playing with just treating the last 5 0xffs in a sequence of at least 5 0xffs as sync bytes (I haven't adjusted the comments to match):

```diff
--- a/Storage/Disk/DiskImage/Formats/NIB.cpp
+++ b/Storage/Disk/DiskImage/Formats/NIB.cpp
@@ -78,9 +78,9 @@ std::shared_ptr<::Storage::Disk::Track> NIB::get_track_at_position(::Storage::Di
 	// from each along all preceding FFs.
 	for(size_t index = 0; index < track_data.size(); ++index) {
 		// This is a D5 AA...
-		if(track_data[index] == 0xd5 && track_data[(index+1)%track_data.size()] == 0xaa) {
+		if(track_data[index] == 0xff && track_data[(index+1)%track_data.size()] != 0xff) {
 			// ... count backwards to find out where the preceding FFs started.
-			size_t start = index - 1;
+			size_t start = index;
 			size_t length = 0;
 			while(track_data[start] == 0xff && length < 5) {
 				start = (start + track_data.size() - 1) % track_data.size();
```

This does allow CLK to recognize PoP's tracks as having just 6 big sectors (the PoP source code refers to 18-sector disks, so maybe each of those 6 big sectors are treated as 3 standard size sectors), but it hasn't improved the boot speed or reliability so I think additional things are wrong. For example, I think this change is needed:

```diff
--- a/Storage/Disk/DiskImage/Formats/NIB.cpp
+++ b/Storage/Disk/DiskImage/Formats/NIB.cpp
@@ -107,7 +107,7 @@ std::shared_ptr<::Storage::Disk::Track> NIB::get_track_at_position(::Storage::Di
 
 	// If the track started in a sync block, write sync first.
 	if(start_index) {
-		segment += Encodings::AppleGCR::six_and_two_sync(int(start_index));
+		segment += Encodings::AppleGCR::six_and_two_sync(5);
 	}
 
 	std::size_t index = start_index;
```

I don't like using a magic number here but you've used it twice already in this method. The disk images I have don't have tracks that start in the last 5 0xffs of a sync block so I don't normally hit this condition but I noticed the problem if I changed the code to write all 0xffs in a sequence of at least 5 as sync bytes:

```diff
--- a/Storage/Disk/DiskImage/Formats/NIB.cpp
+++ b/Storage/Disk/DiskImage/Formats/NIB.cpp
@@ -78,11 +80,11 @@ std::shared_ptr<::Storage::Disk::Track> NIB::get_track_at_position(::Storage::Di
 	// from each along all preceding FFs.
 	for(size_t index = 0; index < track_data.size(); ++index) {
 		// This is a D5 AA...
-		if(track_data[index] == 0xd5 && track_data[(index+1)%track_data.size()] == 0xaa) {
+		if(track_data[index] == 0xff && track_data[(index+1)%track_data.size()] != 0xff) {
 			// ... count backwards to find out where the preceding FFs started.
-			size_t start = index - 1;
+			size_t start = index;
 			size_t length = 0;
-			while(track_data[start] == 0xff && length < 5) {
+			while(track_data[start] == 0xff /*&& length < 5*/) {
 				start = (start + track_data.size() - 1) % track_data.size();
 				++length;
 			}
@@ -91,7 +93,7 @@ std::shared_ptr<::Storage::Disk::Track> NIB::get_track_at_position(::Storage::Di
 			// sync only in the final five. One of the many crazy fictions of NIBs
 			// is the fixed track length in bytes, which is quite long. So the aim
 			// is to be as conservative as possible with sync placement.
-			if(length == 5) {
+			if(length >= 5) {
 				sync_starts.insert((start + 1) % track_data.size());
 
 				// If the apparent start of this sync area is 'after' the start, then
```

This change caused the `if(start_index)` condition to trigger on the PoP disk and caused over 6000 initial sync bytes to be written, which caused CLK to fail to open the disk image.

**Comment by TomHarte** [comment]
I've simplified even further to marking each and every byte that is an affected FF rather than just the beginnings of runs — that avoids the need to do any consideration of wraparound during the second pass. It's not an efficient use of `std::set` but that's hardly important.

(As an aside I also added a little one-slot cache to prevent the same track being transcribed multiple times in succession, which is possible because the caller asks for an update each time the head steps a quarter track, completely oblivious to the underlying disk format being whole tracks only)

Having done that I've temporarily and locally modified `DiskII`:
1. to print a separator when an index hole is posted to `DiskII::process_event` (which isn't otherwise checked for); and
2. to print whatever is in the `shift_register_` any time it is presented to the bus.

So if everything is working appropriately then I should see the same sequence of bytes logged as is present in the original NIB file.

In practice each rotation of the disk seems to have some bytes missing.

I think this is because I'm trivially crossing the data density at which a Disk II can actually read the surface of the disk, which isn't surprising because the fixed NIB track length of 6656 is already really pushing the limits. 

Limiting to permitting only a single run of slip bits per track run gets me very quickly to the Arctic Fox title screen but eventually the left column corrupts slightly and and I don't get beyond. Prince of Persia reliably loads its title screen and intro sequence, only asking for another disk if it is skipped. Which I think is correct to the original?

Anyway, this is as far as I've currently investigated. The pull request is updated with current NIB parsing.

![Clock Signal Screen Shot 08-12-2023, 23 40 22 GMT-5](https://github.com/TomHarte/CLK/assets/1162152/18695975-4423-4d91-9b4d-c537ef1fbfea)

**Comment by ryandesign** [comment]
Thanks for working on this! I agree the nib format doesn't seem ideal, but it's good to support it since there are existing disk images in this format. A couple quick notes now; I'll test your changes later.

> I also added a little one-slot cache to prevent the same track being transcribed multiple times in succession

Thanks, I had noticed those multiple accesses.

> Limiting to permitting only a single run of slip bits per track run gets me very quickly to the Arctic Fox title screen but eventually the left column corrupts slightly and and I don't get beyond.

That matches what happens in OpenEmulator. But Virtual ][ lets you play the game, so it is possible.

Your single run of slip bits is inserted at the end of the first set of 0xffs, right? Which might not be before the first sector? What if you insert slip bits only at the end of the longest set of 0xffs, which should be before the first sector?

> Prince of Persia reliably loads its title screen and intro sequence, only asking for another disk if it is skipped. Which I think is correct to the original?

In OpenEmulator and Virtual ][ you can get to level 1 without being asked to insert a disk.

**Comment by ryandesign** [comment]
> I think this is because I'm trivially crossing the data density at which a Disk II can actually read the surface of the disk, which isn't surprising because the fixed NIB track length of 6656 is already really pushing the limits.

And nib tracks are that large because some part of each track is duplicated or garbage, right? Detecting and removing the duplicate or garbage data is probably difficult. Would decreasing the drive RPM help?

**Comment by TomHarte** [comment]
I have:

1. ensured that 1/4 of each track appears unformatted, to provide some inter-track spacing; and
2. as suggested, marginally reduced disk spin speed, so that the minimal extra data being pushed is still within spec.

That seems to make both the linked disk images work correctly and — although not tested rigorously — reliably.

So I'll let it stew slightly more, but fingers crossed.

**Comment by TomHarte** [comment]
This occurs [seemingly] reliably now:

<img width="1137" alt="Screenshot 2023-12-10 at 22 56 54" src="https://github.com/TomHarte/CLK/assets/1162152/411dafa7-2374-4132-a09b-34485454b7b5">

I'm not especially happy with having had to slow the drives down as it feels like coupling, but on the other hand it's obviously not true that every Disk II runs at exactly 300 RPM so as long as I'm within the bounds of at least one real non-faulty drive then maybe it's okay?

Anyway, landed as modified for now, as the new version is definitely a step forwards.
