### ISSUE TITLE
Question: Where is config stored? I'd like to start fresh for demonstration purposes.

### ISSUE THREAD

**Issue by IO101010** [TomHarte/CLK#1295]
I've dragged in a ROM as requested, and the application launched. This is great, but I'd like to demo how to do it from scratch for others. I'm on macOS. Can you tell me what to do to "reset" the application?

Great work, by the way.

**Comment by TomHarte** [comment]
ROMs are stored in whatever Apple identifies as the user's `NSApplicationSupportDirectory`; because the app is sandboxed that's likely to be:

`~/Library/Containers/TH.Clock-Signal/Data/Library/Application Support/`

I dare imagine you can delete the entire folder, but just removing `ROMImages` should be sufficient.

Let me know whether that works; I'll leave the ticket open for now.

**Comment by IO101010** [comment]
That works, thanks so much!
