### ISSUE TITLE
Mac OS guest on macOS host: “The document [any disk image file] could not be opened.”

### ISSUE THREAD

**Issue by boredzo** [TomHarte/CLK#1325]
I'm trying to use Clock Signal as a Mac emulator. I'm using the 2024-01-22 release on Monterey on an Intel Mac. I've never used the app before so this is first-run setup.

I've tried both the hard drive image that I usually use with Mini vMac and a floppy image (both should be HFS; the former definitely is) and both give me a bare-bones “The document … could not be opened” error. No output is emitted on the console/stderr.

<img width="532" alt="Here's a screenshot of a simple macOS alert that says “The document ‘6.08_40MB.img’ could not be opened.” with no further explanation. The only button is OK." src="https://github.com/TomHarte/CLK/assets/49781/8f435364-dddc-4340-98e2-b749f146a723">

Reading tutorials such as [this one](https://www.emaculation.com/doku.php/clocksignal#initial_launch) suggests that (1) this is supposed to work, and (2) I should get asked for some ROMs. I haven't been asked for some ROMs. 

The name of the image file makes no apparent difference. I tried both .img and .dsk. Same result either way.

I also tried opening a bare classic-Mac-OS application file (ResEdit). Clock Signal does not even show the file as openable; it's dimmed out in the Open dialog.

**Comment by ryandesign** [comment]
At the moment, the Macintosh emulator in Clock Signal only supports 800K and 400K floppy disk images that are exactly 819,200 bytes or 409,600 bytes in size, respectively. It doesn't support bare applications, only disk images.

It does not support Mini vMac-style arbitrarily-sized floppy disk images. (Mini vMac does not support hard disk images that have partition tables; it only supports partitionless floppy disk images.)

See some words I wrote about possible improvements to this in #768.

You won't get asked about ROMs until Clock Signal has figured out what kind of machine it needs to start, and if it can't identify your disk image then it doesn't know what kind of machine to start yet.

**Comment by boredzo** [comment]
Ahhh, I see. I padded the floppy image to 819,200 bytes and then Clock Signal recognized it happily.

I agree with your recommendations on that issue. Mac disk images are _routinely_ not exactly 409,600 or 819,200 bytes, including images that came from Apple—the floppy image I just used did, and before padding, it's 794,112 bytes. (It's the Guided Tour of Macintosh Plus, as obtained from “Phil and Dave's Excellent CD” volume 1. And yes, that was an official Apple release for developers.)

Even if there's some technical reason why the image needs to be made available to the guest system as exactly 409,600 or 819,200 bytes, this is a “data set fits in RAM” problem; the whole image could be slurped into a fixed-size zeroed-out buffer of either size, if it isn't already. The length of the source image file is irrelevant except as a lower bound for the buffer length.

Anyway, it seems like this is a duplicate of that issue, so I'll close this one. Thank you for your response.

**Comment by ryandesign** [comment]
I forgot to say that Clock Signal also supports (and originally only supported) Disk Copy 4.2 images which are validated without needing to check their size (by checking fields in their header). The 819,200- or 409,600-byte size requirement applies only to raw sector dumps (which don't have headers), not to Disk Copy 4.2 images. It seems logical that a raw dump of all disk sectors would always be the exact size of all the sectors so I'm curious about your disk image where that was not the case.

Thank you for pointing out Phil and Dave's Excellent CD, which is a most excellent name for a CD. The copy of the Macintosh Plus Guided Tour on that CD is in DART format. DART was the Apple-internal predecessor of Disk Copy. Clock Signal doesn't support DART disk images so trying to open that disk image in Clock Signal would not work today but in my opinion DART support would be a great enhancement to Clock Signal, if any documentation about its format can be found or if it can easily be reverse engineered. Its checksum algorithm is given in an appendix of the DART manual but I couldn't find a description of the rest of the format. It wouldn't surprise me if it were in ways similar to the Disk Copy format but I haven't tried to compare them. DART disk images can store Macintosh, Apple II, Lisa, and MS-DOS disks, so this could be useful not only for the Macintosh part of Clock Signal.

But you said you converted it. What format did you convert it to and what program did you use to do that? I tried converting it using Disk Copy 6.3.3. It gave me four format options: read/write, read-only, read-only compressed, and Disk Copy 4.2. The Disk Copy 4.2 setting resulted in a file that worked fine in Clock Signal. Using the read/write setting I got an 819,200-byte file that also worked fine in Clock Signal since it's the right size for an 800K raw sector dump and it begins with the `4C4B` magic number that indicates a bootable disk. The read-only setting gave me a 794,112-byte file which is the size you said you got so I'm betting this is how you converted it. It also begins with the `4C4B` magic number but is too short. Padding it with nulls allowed it to boot up in Clock Signal. A way to do the padding that doesn't require installing another tool is:

    dd if=/dev/null of="Name of Disk Image.img" bs=1 count=1 seek=819200

The read-only compressed setting gave a much smaller 471,617-byte file that also begins with the `4C4B` magic number. Padding this file to 819,200 bytes did not work; Clock Signal identified it as a Macintosh disk but could not boot it. So the question isn't whether Clock Signal could pad a shorter file to the expected size. Sure, it could, but that's evidently not always going to result in a usable disk. And Clock Signal uses heuristics to analyze a disk image to determine what kind of disk image it is to know what kind of emulator to start. The way that Clock Signal currently identifies a Macintosh disk is that it is a valid Disk Copy 4.2 image, or it begins with the magic number `4C4B` or `0000` (the latter indicating a non-bootable disk) and is 819,200 or 409,600 bytes long. If we remove the size constraint for non-Disk Copy 4.2 images, that leaves only a check for the first two bytes of the file which is not specific enough. Disk images for non-Macintosh systems (and plenty of files that are not disk images at all) might match that check so a more thorough analysis of the disk image would need to be performed, which I think is a good idea as per the other ticket.

So why did padding one of the images work and for the other it didn't? Looking at the read/write, read-only, and read-only compressed images in ResEdit, they all contain a `bcem` resource, and based on some quick searching this resource is essential to understanding the structure of the data fork. The first two bytes of the resource, for example, tell whether the data fork is compressed or not. I found some [very incomplete documentation of the `bcem` resource here](https://github.com/roydmerkel/Retro86-windows-build-helpers/wiki/NDIF-Image-Format). Elsewhere I saw someone describe the contents of this resource as compression dictionaries. So without this resource you cannot understand the disk image, and therein lies the problem because the resource fork is not preserved when files are transferred to non-Macintosh systems. This makes this disk image format unsuitable for storage on the Internet. (Disk Copy 4.2 format doesn't have this problem since it's fully contained within the data fork.) So if any of this type of disk image exists on any web server, it's unusable, incomplete, corrupt—except that Clock Signal can infer that it's a complete uncompressed file based on its size. It would be possible for someone to wrap such a disk image in a container that preserves the resource fork, such as MacBinary or BinHex, and upload that container to a web server. If that's a common practice, then Clock Signal might conceivably be enhanced to support reading MacBinary or BinHex files (they're simple well-documented formats) so that it could access the resource fork of the embedded file, interpret its `bcem` resource, and reinflate the disk image correctly. You're on a modern Mac, which still has the ability to store resource forks in its file system, so if you preserved the resource fork when transferring that converted disk image from your vintage Mac to your modern Mac, Clock Signal could also conceivably be enhanced to read its resource fork directly.

**Comment by boredzo** [comment]
Yeah, I used Disk Copy 6.3.3 to convert the image from the CD to a read-only uncompressed image.

Interesting that the read-only and read-write images are different sizes. I guess the read-write image includes the full 800K as disk sectors, while the read-only image only contains extant data and leaves it up to the Disk Copy disk-image driver to fill in zeroes for any unused sectors requested.

(Your note about the `'bcem'` resource being present on uncompressed images makes me wonder whether it's possible for a read-only uncompressed NDIF image to leave out unused sectors that are in the middle of a volume. Treating such a volume as a raw image would lead to incorrectly reading it. Hmmm. Something I should look into sometime…)

As for further checks:

- A volume is HFS if it has 0x4244 at offset +0x200 (i.e., just after the boot block, which is the one that starts with 0x4C4D if it's filled out).
- A volume is MFS if it has 0xD2D7 at offset +0x200.
- A volume is bootable if it has a populated boot block AND the files named in the boot block exist in the volume following the boot block. Most important are the System file and the shell (Finder).
- Both MFS and HFS includes the length of the volume (in allocation blocks, along with the size of an allocation block) in the volume header, so a truncated (or compressed, or corrupt) image can be detected by comparing the true length of the volume to what the header says it should be. Note that the first allocation block is _after_ the volume header (until HFS+, which changed the counting so that the first allocation block includes the boot block).
- Apple Partition Maps also indicate the length of each partition.
- One caveat: I've imaged CD-ROMs that were shorter than their partition map or volume header claimed they would be—not by much, but still. I might advise allowing the user to try to use an image that's too short, but mounting it read-only.

I think the only disk images I've ever seen wrapped in MacBinary or BinHex were distributed by Apple themselves, especially the _self-mounting_ images (.smi). These are essentially the same as an NDIF (Disk Copy 6) file, but with application resources added on so it can be launched on System 7 or later and will mount itself. Users creating disk images was never much of a thing on Classic Mac OS; people usually made StuffIt archives rather than disk images.

In the modern era, the common practice for the distribution of disk images on Mac abandonware sites is to use raw disk images or the read-only uncompressed format, neither of which needs the additional resources. (Besides disk images, StuffIt and other archive formats are also used.) The prevailing wisdom on Macintosh Garden regarding compressed disk images is “don't use them; you'll need to wrap them in a StuffIt archive anyway, so make an _uncompressed_ image and Stuff that”. ZIP archives aren't used because only macOS's Archive Utility knows to look for and decode the AppleDouble bits.

Arguably a better solution to the NDIF problem would be UDIF (.dmg) support. UDIF didn't exist until the Mac OS X era, but at least it's possible to convert NDIF to UDIF on a modern Mac. But supporting it runs into the problem that neither format is really documented as far as I've found. (For what it's worth, I've seen indications that UDIF is some sort of flattened version of NDIF, but not a lot of specifics beyond that.)

Canonical documentation:
- MFS: “Inside Macintosh” volume IV.
- HFS and the boot block format: “Inside Macintosh: Files”.
- Apple Partition Map (while I'm listing off references): “Inside Macintosh: Devices”.
- AppleDouble: https://www.rfc-editor.org/rfc/rfc1740#appendix-B (the fact that it's used in modern Mac ZIP archives is not documented but can be observed through inspecting the ._-prefixed files in a hex editor).

“Inside Macintosh” (both the older Roman-numbered volumes and the less-old topic-titled volumes) can be downloaded from VintageApple.org.

**Comment by ryandesign** [comment]
Thanks for all that documentation; it's more than I had found earlier.

Checking whether a disk is bootable is not necessary, I think. A user could want to boot a machine with a bootable image and then insert a non-bootable image to use its data.

True, there were self-mounting images, but were any of them actually of 400K or 800K floppy images? I don't remember that being the case, and browsing an archive of download.info.apple.com just now, the .smi.bin entries I found did not look like they were the right size.

DiskCopy 4.2 couldn't mount disk images at all; it could only convert between disk images and real floppies. Clock Signal already supports these disk images. As I recall, it was ShrinkWrap that introduced the innovation of being able to mount disk images in the early 1990s. By the late 1990s, Apple had added that feature to Disk Copy 6, and later added self-mounting images, but by that time, floppy disks were no longer involved in the process; instead, we were downloading images, mounting them, and copying the files to our hard drives. And because of this change in usage, there was no need for the disk images to remain limited to the size of floppies. Disk images, self-mounting or not, were often just as big as was needed to contain the data on them. For an application update, the image was often smaller than a floppy. For system software installations, it was often much larger than a floppy. Sometimes a single disk image was split into an .smi and additional .part files. (Remember System_7.5.3_01of19.smi.bin?) Clock Signal cannot deal with these arbitrarily-sized disk images because it does not present disk images to the emulated machine; it presents a floppy disk drive to the emulated machine, and in the case of the Macintosh Plus emulation it is an 800K floppy disk drive so it can only deal with 400K or 800K disk images.

Downloads of earlier system software images on download.info.apple.com, from before the advent of .smi files, were often packaged as 800K disk images enclosed in .sea.bin files, where the self-extracting archive was created with DiskDoubler (for example  SSW_6.0.8-800k_Disk1of4.sea.bin). It would be great to be able to use those files in Clock Signal directly but the DiskDoubler format was not open or documented. The Unarchiver claims to have nearly completely reverse-engineered the DiskDoubler format, so maybe Clock Signal could use [the unarchiver's library](https://github.com/MacPaw/XADMaster) to gain support for DiskDoubler, MacBinary, BinHex, and even some StuffIt formats. However, it was unable to decompress the one DiskDoubler .sea.bin file I gave it just now so I filed a bug with them about that.

**Comment by boredzo** [comment]
>True, there were self-mounting images, but were any of them actually of 400K or 800K floppy images? I don't remember that being the case, and browsing an archive of download.info.apple.com just now, the .smi.bin entries I found did not look like they were the right size.

Probably not, because by the time Apple introduced .smi images (mid-1990s IIRC), FDHDs/SuperDrives had been standard in Macs for years.

At any rate, that was the main source of MacBinary-encoded images that I remember. Otherwise other formats were typically used.

It occurs to me that being able to feed a .smi and its associated .parts to an emulator and have the emulator automatically reintegrate them and present the complete volume to the guest as one disk would be a pretty cool feature. Probably a ton of work though, on top of the work that would already be required to implement NDIF (including the two or three different compressors that were used with it).

**Comment by ryandesign** [comment]
Yes, that would be cool, but again the problem is how do you present that to the machine? If you don't want to patch the ROM to replace the floppy disk driver like Mini vMac does, your options are a fixed-size floppy disk or a SCSI hard disk that needs partition tables and, at least on physical hardware, need to be attached before the machine is powered on and can't be detached until the machine is off. Even if the electrical issues of possibly frying the computer or the drive don't apply in emulation, there's still the problem that the OS doesn't go scanning for new SCSI devices all the time, so if you attached one after startup it wouldn't show up on the desktop.

What could be interesting is an emulated SCSI device that acts like a SyQuest, Zip, or other removable drive, but which accepts disk images of any size. Tom touched on this idea as well in the other ticket when he suggested a SCSI floppy drive for supporting high-density floppies. The problem, though, will probably be that the OS has no built-in support for being notified by such a SCSI device that a new disk has been inserted. SyQuest and Zip required the user to install drivers to gain that feature, so Clock Signal would either have to emulate a SyQuest or Zip or similar drive well enough that its driver could be used, or a new driver would have to be written specifically for Clock Signal. And having to install any driver on a disk image kind of defeats Tom's idea of an emulator that you can use simply by double-clicking any disk image you have. Well, you could still do that: SyQuest and Zip drives typically worked without a driver if you had a disk inserted at startup, they would just act as a non-removable hard drive.

And of course one final problem with doing this through SCSI would be that it limits you to the Macintosh Plus or later, since there is no SCSI on the Macintosh 128K, 512K, or 512Ke, at least not without third-party expansion boards. The 512K and 512Ke could be supported by emulating a Hard Disk 20, but the HD20 isn't convenient to use on a 512K since it needs a special startup floppy since HFS is not in the 64K ROM, and the HD20 isn't supported by System 6 or later or by later machines. Mini vMac's approach may not be authentic but it really is quite nice since it works across the entire range of Macs that have floppy drives without requiring anything to be installed on the disk images.
