### ISSUE TITLE
Electron: flickering

### ISSUE THREAD

**Issue by polluks** [TomHarte/CLK#1390]
It this real?
https://github.com/0xC0DE6502/manic-miner-2021-releases/

**Comment by TomHarte** [comment]
It's hard to imagine it's anything other than an emulator issue. I'll try to figure it out.

**Comment by TomHarte** [comment]
Very, _very_ superficial testing definitely appeared to confirm a bug on the emulator's side; the game itself seemed to be reliably setting the palette to black at end-of-display and back to appropriate colours at the real-time clock frame midpoint.

No further leads on what the bug actually is yet; it's really curious.

**Comment by TomHarte** [comment]
I found a bug in the emulator's logic for triggering interrupts; most likely to affect every other real-time clock interrupt (i.e. the mid-frame interrupt), which is exactly what was causing Manic Miner not to restore its palette every other frame.

Specifically: the test for "has interrupt passed" was `if(start_of_period < interrupt_time && end_of_period >= interrupt_time)`, which behaves incorrectly if the period overlaps end of frame because it doesn't properly deal with a circular range.

Fixed.

I guess it's pure luck that other titles I've tried happen to draw to the video area at a suitable time to make the period not problematically overlap end-of-frame. But it was a definite, identifiable bug.

**Comment by 0xC0DE6502** [comment]
Well done! =)

**Comment by TomHarte** [comment]
Having had a quick further review, I think I'm likely to rip out the current implementation and replace it with an as-literal-as-possible transliteration of hoglet's FPGA reimplementation of the ULA. Besides benefiting from everything learnt since I first wrote this code c.2016, it'll be easier to track any future discoveries.On 1 Sep 2024, at 06:26, 0xC0DE ***@***.***> wrote:﻿
Well done! =)
