### ISSUE TITLE
Some Spectrum DSK disk images are misidentified as Amstrad DSK images, some are not recognized at all.

### ISSUE THREAD

**Issue by hippietrail** [TomHarte/CLK#1392]
I downloaded 7 random Speccy DSK images from [Planetemu.net](https://www.planetemu.net/roms/sinclair-zx-spectrum-dsk) to play with analysing the DSK and EDSK file formats.

While they all work in Retro Virtual Machine, only three work in CLK:
- Arkanoid - Revenge Of Doh (1988)(Imagine Software).dsk (EDSK)
- Cybernoid II (1988)(Hewson Consultants).dsk (EDSK)
- Dan Dare II - Mekon's Revenge (1988)(Virgin Games).dsk (EDSK)

These two are misidentified as Amstrad disks:
- Ghouls 'N' Ghosts (1989)(Software Creations).dsk (DSK)
- Jet Set Willy 128 (19xx)(-).dsk (DSK)

These two cause the "The document “*.dsk” could not be opened. error:
- Chase H.Q. (1989)(Ocean Software).dsk (EDSK)
- Loads of Midnight (1987)(CRL Group).dsk (EDSK)

----
I thought they might work if instead of using "Open" I used "Insert" from a window that's already running as a Speccy. But I couldn't find a way to reset so it would boot off the new media.

OK if I do "New" and select "Spectrum +3" and then "Insert" then they all work.

**Comment by TomHarte** [comment]
Not that it resolves anything, but if it saves you a few clicks in the meantime then you can also just drag and drop disk images over a running window to insert the disk.

That said, the problem is what you'd probably guess — the emulator fails in its analysis of disk contents and then, crucially, declines to pick a horse. Which is stupid because the emulator already has runtime selection as its intended mechanism to work around that, it's just that I've yet to implement the relevant hooks into the Spectrum and CPC.

I'm going to poke around the analyser first to see whether I can make it work before machine launch, otherwise I'll fall back on the dynamic mechanism.

**Comment by TomHarte** [comment]
Notes to self:

* Chase HQ, Ghosts 'n' Ghouls and Jet Set Willy all use the non-boot-sector fallback on LOAD "DISK" [as described here](https://retrocomputing.stackexchange.com/a/14602/4147) that I was not previously aware of and that's why the emulator fails to recognise the ZX Spectrum as a potential target;
* I strongly suspect Loads of Midnight falls under that rule too, but also subject to the "If the first ten bytes of the sector are all the same, assume that they are [the usual disk parameter block]" before the CP/M-format directory can be read, but did not verify.

So evidently I need to try to respect the rules linked better than at present.

**Comment by hippietrail** [comment]
Nice! Verified by building on my Mac.
