### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by stevexyz** [TomHarte/CLK#249]
Where to find executables files? There are unix versions?

**Comment by TomHarte** [comment]
There are no ordinary UNIX versions yet, only Mac builds. There are two things I want to do before building more generic front-ends.

1. my [slightly] thread-juggling time counter is currently Mac-specific because I was negligently unaware of std::chrono, but that's an easy port being one small class; and
1. although there's a common interface for key up/down propagation, there's currently no attempt to generalise key mapping. It is still assumed that each host machine know how its keyboard should map to an Oric and, separately, how it should map to an Electron and, separately, how it should map to a CPC, etc. Which is too much maintenance cost. I need to come up with an intermediate form, I think.

I'll keep this issue open as I want to work on exactly those two things in the near future and then install one or both of Qt and command-line SDL machine launchers. There shouldn't be that much to either problem once the blockers are resolved: provide an OpenGL viewport, be able to pipe audio outward, be able to pipe the keyboard inward.

**Comment by TomHarte** [comment]
(though the Mac binaries are in the 'Releases' tab — https://github.com/TomHarte/CLK/releases — and other releases will be deposited there also)

**Comment by TomHarte** [comment]
Update: (1) is resolved. A standard C++11 implementation is offered for the ordinary timing mechanism.

**Comment by TomHarte** [comment]
(2) is largely resolved, though I'd like to spend a little extra time on clean-ups. It was actually a really helpful process, as I discovered I'd missed a couple of Vic-20 keys entirely.

I also spent some time on a tool-assisted search for inadvertent undefined behaviour, and uncovered various things like unaligned writes in the CPC and Electron display code that are undefined behaviour and would likely have been problematic on an ARM.

So progress continues.

**Comment by stevexyz** [comment]
I do not have Mac.
I'm lloking forward to see how it is the Linux version! :)
Happy hacking!

**Comment by TomHarte** [comment]
Update on this: an SDL-based port now compiles and runs on the Mac. It's completely without a UI or joystick input, and suffers worse audio latency than the native version, but likely won't be more than ten lines and a build system away from functioning on other OpenGL 3.x+ SDL platforms. So something very provisional may be forthcoming for Linux soon.

**Comment by TomHarte** [comment]
[This](https://github.com/TomHarte/CLK/files/1463441/clksignal.gz) is my very first attempt at a command line version build under Linux. There's no UI. You'll need to launch with `clksignal [disk/tape/cartridge file]` and it's going to expect computer ROMs to be in /usr/share/CLK or /usr/local/share/CLK but isn't going to give you much information if they're missing.

On my virtual machine SDL simply fails to initialise its display. So I'm looking into that.

Let me know if you spot this and have any success or failure with that binary.

**Comment by TomHarte** [comment]
Oh, also: it doesn't yet do anything to try to pipe joystick input to the machines. So an Atari 2600 game is a good first one to try because there are no system ROMs. But you won't be able to play it right now. See the ROMImages folder in this repository for lists of the ROM files expected for each system. E.g. for an Electron one file you'll want is `/usr/local/share/CLK/Electron/os.rom` (or the non-/local equivalent).

**Comment by TomHarte** [comment]
This is now believed fixed; the latest release has a functioning build system and is believed overwhelmingly to work correctly under Linux. I'll be filing additional bugs as they arise.

Unrelated: I just hopped onto your Github page; greetings to you from a recent Xoogler.
