### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

### ISSUE THREAD

**Issue by ghost** [TomHarte/CLK#432]
Hi
When I try to build, I have this error : 

'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

OS : Manjaro

Thank for your help.

**Comment by TomHarte** [comment]
Almost certainly I've subconsciously typed an emdash into a source file somewhere and it's been saved out in unicode. Actually, I've probably done that quite a lot. I'll have a hunt for non-ASCII characters.

**Comment by TomHarte** [comment]
As per the pull request that alleges to resolve this, all non-ASCII characters in source files are now gone, and I think the direct offender was a ß that I will have typed by accident while intending to save a file.

**Comment by MJB-G** [comment]
Thank, but I still have the same message.

**Comment by TomHarte** [comment]
I assume you pulled, etc, so: are you given any more information — does it tell you anything about which file is being inspected when the error occurs?

I'll try to install Manjaro for myself; in case it's a language issue, which locale do you ordinarily use?

I was pretty confident it would be the stray ß because the UTF-8 for that is `c3 9f`, but I guess that was just coincidence. I'm also now able to compile on my machine while specifying `-finput-charset=ascii`, making me believe I was completely 7-bit safe.

**Comment by MJB-G** [comment]
The exact message is : 

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [main.o] UnicodeDecodeError : 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
scons: building terminated because of errors.

**Comment by TomHarte** [comment]
I'm still having no luck reproducing this.

I installed Manjaro XFCE 17.1.10 64bit, used its package manager to install scons, and then cloned and built CLK with no issues.

Which version of scons are you using?

**Comment by MJBG** [comment]
Works with  :

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by TomHarte** [comment]
Fantastic, thanks @MJBG ! As is almost certainly obvious from the year's delay, this is a problem I remained largely clueless about. The penny never quite dropped that the error would be from the Python interpreter rather than the C++ compiler.

Fix incorporated, optimistically closing issue.
