### ISSUE TITLE
Oric (1 or Atmos) with Microdisk produces random colorful jittering screen

### ISSUE THREAD

**Issue by nekoniaow** [TomHarte/CLK#448]
For both releases 2018-04-13 and 2018-05-15, on macOS Sierra (10.12.6):

1. Launch Clock Signal
2. Go to menu "File -> New ..."
3. Select Oric1 or Atmos (both cause the issue)
4. Select "Microdisk"
5. Start the guest machine

This will produce a very colorful animated random screen.
The guest computer does not seem to respond to any input thereafter.

Note that dropping a disk image such as the one listed in the Defense Force forum post linked below generates a non animated version of that screen, at least for release 2018-05-15.
Post: http://forum.defence-force.org/viewtopic.php?p=17531#p17531

**Comment by TomHarte** [comment]
That guess wasn't exactly right; actually I'd inverted the meaning of the Microdisc's overlay RAM control while factoring out some constants that are shared with 8DOS. So an Oric with a Microdisc was disabling the BASIC ROM when it meant to enable it, and thereby jumping into overlay RAM and no doubt either looping forever or hitting one of the 6502 jam instructions.

Will be fixed in the next release; indeed I might rush a release because it's a fairly major error.

**Comment by nekoniaow** [comment]
I confirm this is fixed in the 2018-05-24 release.
Thanks!
