### ISSUE TITLE
Amstrad CPC: emulation keyboard and key pressed

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#464]
The following code detects if a key has been pressed on a given row:
```
test_keyboard:
        DI
        LD BC,#0XF782
        OUT (C),C
	LD BC, #0XF40E
	OUT (C), C
	LD BC, #0XF6C0
	OUT (C), C
	.DB #0XED,#0X71        ;    OUT (C),0
	LD BC, #0XF792
	OUT (C), C
	DEC B
	OUT (C), A
	LD B, #0XF4
	IN A, (C)
	LD BC, #0XF782
	OUT (C), C
	DEC B
	.DB #0XED,#0X71        ;    OUT (C),0
	CPL
	EI
	RET
```

To test if any key was pressed I go from a = 0x40 to 0x49; and if any call return a != 0, then there was a key pressed.

This works with other emulators and the real hardware but in CLK looks like there's always a pressed key (although is not the case).

**Comment by TomHarte** [comment]
That's immediately a mystery. I'll get right onto it.

**Comment by reidrac** [comment]
Now thinking about it I wonder if it is something related to the input in my system and not the emulation.

I'm running Debian Stretch with XFCE, in case that helps!

**Comment by TomHarte** [comment]
I've added an extra safety measure in #466 — clearing the emulated key state when switching between full screen and windowed mode. Does that help any?

**Comment by reidrac** [comment]
No change. I can reproduce the issue even without going full screen.

**Comment by TomHarte** [comment]
I've added some basic stdout logging to https://github.com/TomHarte/CLK/tree/CPCKeyboardTest to try to get some more information on this. Would it be possible to give it a go and let me know  what it outputs?

**Comment by TomHarte** [comment]
No, it's helpful — it rules out the idea that your system (or, rather, SDL when interpreting your system) is supplying a phantom key press to which the emulator is responding correctly, and establishes that the problem is definitely the emulator incorrectly describing the current input state.

(all keys that are considered within the usual-ish range but don't have a specific CPC meaning are mapped to `copy`. So it wouldn't actually have needed to be a key that corresponded to anything)

So knee-jerk guesses of most likely culprits:
* a misinterpretation of input/output selection in either the PSG or the PPI; or
* accidental undefined behaviour.

I haven't actually tried the code you supplied on Linux, just on the Mac, so that plus the Clang undefined behaviour analyser might be worthwhile as to the second option. I've looked at the leaf stuff of keeping ten bytes and toggling bits to death now, I think. It's so straightforward that I'm hopefully not being snow blind.

**Comment by TomHarte** [comment]
Follow-up on this: do you definitely never call with A outside of the range `0x40` to `0x49`?

I discovered one bug: even if the AY was not in reading mode, you could still read the last thing it loaded the bus with during a reading mode. So with your code, if A is outside of that range then you don't select reading mode and at the IN will read something not defined by that code segment.

Probably unrelated. But fixed.

**Comment by reidrac** [comment]
That fixed it. Turns out the library I use to handle the keyboard (cpcrslib) had a bug. instead of 0x40 it used 40; which makes that look go from 0x28 to 0xa9 :man_facepalming:. I didn't see it until you mentioned this.

Now I guess recent games that used cpcrslib will work with CLK! I'll report this to the library author.

Feel free to close this bug.

**Comment by TomHarte** [comment]
Cool! Then closed. I also found http://cpctech.cpc-live.com/docs/psgnotes.htm that covers some other behavioural corner cases, so I'll try to implement that. But it won't affect this ticket. So closed.

**Comment by reidrac** [comment]
It kind of makes me happy you fixed the 464 issue ;)
