### ISSUE TITLE
Wrong sprite patterns in Robocop (Sieco)

### ISSUE THREAD

**Issue by grauw** [TomHarte/CLK#496]
Hey TomH, when I play Sieco_RoboCop_(1992)(Sieco).rom the sprites look wrong in CLK:

<img width="600" alt="schermafbeelding 2018-07-14 om 12 41 01" src="https://user-images.githubusercontent.com/772052/42723718-dc18e050-8763-11e8-9ff8-2d1da720e99b.png">

Compare:

<img width="640" alt="schermafbeelding 2018-07-14 om 12 41 33" src="https://user-images.githubusercontent.com/772052/42723722-e703ad4c-8763-11e8-8a67-a6ff6f2ba666.png">

**Comment by TomHarte** [comment]
My immediate guess is that sprites are in 8x8 mode but for some reason I'm painting them as though they're 16px wide. Two bytes are always fetched per sprite because that's true of a real TMS so it's most natural when reproducing its timing diagram to end up fetching two bytes, but for some reason I'm not discarding the second.

Just a guess. I'll look into it.
