### ISSUE TITLE
Some colors in MSX palette too uniform

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#526]
I'm not sure if this is something that could be improved or no, or if it is a problem at all (sorry).

I've noticed the palette implemented by CLK on MSX is quite bright and few colors look almost the same (at least on my screen). I know there's no official RGB values for the MSX palette, but compared with other MSX emulators, CLK looks too uniform (specially on reds).

May be this bug report on OpenMSX can explain it better than me: https://github.com/openMSX/openMSX/issues/1024

With display=composite looks slightly better. This report applies specially to rgb (although svideo is almost the same).

Thoughts?

**Comment by TomHarte** [comment]
The TMS is one of only two systems that think in RGB internally, which in principle makes this very easy to fix, but I think it might actually be symptomatic of a mishandling of composite colour calculation elsewhere. Or I've just failed to allow for gamma correction in sourcing the RGB values that I have.

Probably the correct work item is just to use the YPbPr values directly. It's even one less transformation for composite and S-Video modes, so slightly less work.

**Comment by reidrac** [comment]
Actually, svideo colors look a bit muted, but you can see the difference between reds.

**Comment by TomHarte** [comment]
That's further evidence that something is going wrong in the scaling of composite video after filtering off of the chrominance signal. Which is very easy to say, but I'm damned if anything jumps out on review, and frustratingly much of it is in GLSL so no step debugging, no logging, and at present I've nothing set up to unit test anything that goes to the shader.

I'll aim to give YPbPr a whirl as soon as I've finished my current Apple II task; if S-Video is then correct but composite is still washed out then that'll confirm a luminance scaling issue. If S-Video still doesn't look correct then either I've misunderstood what YPbPr is, or the next thing to check is probably the gamma conversion.

For the record, I've implemented only an NTSC MSX, so if the code is functioning then it should end up believing that both the machine and your monitor have a gamma of 2.2*, and apply a no-op gamma transformation. So hopefully that's a non-issue. But it's in the mix.

* guaranteed on macOS since 10.6; assumed by me also for SDL targets in lieu of better information, as it has also been the Windows gamma forever and therefore I'm working on the assumption that Apple was being an oddball with its prior 1.8.

**Comment by reidrac** [comment]
Thanks for the comment, I was convinced that you were implementing PAL and I was VERY confused that my code seemed faster on it.

60Hz, that explains it; but then I would expect bit 7 on 0x002b to be 0 and it is 1 instead. Not sure if I'm getting this wrong, but when I try an NTSC MSX1 on OpenMSX that value is correct, so I wonder if there's something wrong in CLK. Probably a different issue.

**Comment by TomHarte** [comment]
I think you're right; I grabbed the BIOSes from Marat's website based on the possibly questionable logic that if somebody else has been distributing them for twenty years, they're probably not going to be problematic. Also it makes them easy to locate for people who install the SDL version. But if they're the wrong files then those are not really compelling arguments.

**Comment by TomHarte** [comment]
Re: colours again; there was an error in final composition. See attached for 'before' and 'after' — note especially the lines down the centre of the road. I'm looking into the ROM identification issue.

![before](https://user-images.githubusercontent.com/1162152/45270937-9a212380-b470-11e8-9b2d-998645d62f72.png)
![after](https://user-images.githubusercontent.com/1162152/45270936-9a212380-b470-11e8-93d3-1713bd5c000b.png)

**Comment by reidrac** [comment]
With that change I see a difference now and is more what I was expecting :+1:

**Comment by TomHarte** [comment]
I'm happy with the colour fix now, I think, so I've split the BIOS region issue into #551 .
