### ISSUE TITLE
Noise on key press

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#527]
When reading the keyboard status I've noticed there's a *tick" (noise) on the audio output, not present in other emulators.

**Comment by TomHarte** [comment]
I had the feeling that was the machine's deliberate doing, via 8255 Port C, but that doesn't preclude the possibility that I have it wrong in the mix, and I'm currently not high-pass filtering anything which might have an effect: the implementation of these things can be such that at low frequencies only the toggle in one direction is audible because the high level leaks back down to zero.

I'll look into it.

**Comment by reidrac** [comment]
I think this is not a bug. I've seen the same behavior with OpenMSX and a Toshiba HX-10.

Feel free to close it.
