### ISSUE TITLE
Blurry rendering on Linux

### ISSUE THREAD

**Issue by reidrac** [TomHarte/CLK#618]
I've noticed this after the latest release. The screen looks OK and after a second or so it's a bit blurry.

This is MSX running default (RGB I assume).

![Screenshot_2019-04-18_23-25-45](https://user-images.githubusercontent.com/120189/56395204-8ffaab00-6231-11e9-9de6-68012acbb0ee.png)

Not sure if this is a bug, but the fact that it changes makes me think that may be this is not intended.

**Comment by TomHarte** [comment]
That image doesn't actually look blurry to me, so maybe I'm the problem but otherwise some off the top of my head things to check:

- that RGB really is the MSX default; and
- that my sampling constants are adapting correctly to resolution changes.

**Comment by reidrac** [comment]
For example:
![image](https://user-images.githubusercontent.com/120189/56635277-f8e08980-665c-11e9-8c3c-f6f442660137.png)

This is how it looks after some seconds, but not initially. That border around the text.

**Comment by TomHarte** [comment]
Oh, okay, I think I've figured this out in principle, though I've not yet fixed it. The 'after a few seconds' gives it away.

So the newer renderer allows edges that aren't technically entirely sharp, because it's a more visually accurate way to handle non-integer scaling. What you see for the first few seconds is that working as intended. What you see afterwards is it malfunctioning.

I think it's interacting poorly with the dynamic intermediate buffer size selection that I added as a safeguard against my lacklustre GLSL. Specifically, on your machine I think it is making a probably-bad choice to use a smaller work buffer, then a definitely-bad choice in window size.

You can hack around the problem for now by finding the function `bool Metrics::should_lower_resolution()` which is the final one in Outputs/DisplayMetrics.cpp, and just having it always return `false`.

I'll need to figure out what the smartest thing to do here is. I mean, ideally, get better at writing GLSL so that my code is never too slow, but also probably be smarter about sampling window size selection. And also probably be much smarter on when a resize selection is made. And possibly be smarter about picking the minimal acceptable size, which at the minute doesn't factor in a machine's pixel clock (and, therefore, it's pixel aspect ratio) at all.

Hopefully I'll be able to come up with something in the next few days.

**Comment by reidrac** [comment]
That didn't help. Take your time :)

**Comment by TomHarte** [comment]
I think I'm going to fold this mentally into my ongoing efforts to add emulation of the early Macintosh, on the grounds that the Macintosh has a sharp monitor at a comparatively high resolution for machines covered by this emulator, which is pure 1bpp black and white so artificial softness is unambiguous, and right now I'm implementing it in the most obvious way possible, which means it's slow. So it is prone to trigger attempts by the video subsystem to reduce working cost.

I'm away for a couple of weeks starting later today, then it'll probably be a week or two until the Macintosh is doing anything reasonable, then I'll have what I hope will be the really good test case. So I'll test my suspicions then, and make sure I merge whatever results as a separate work item.
