### ISSUE TITLE
How to load a disk for Apple II

### ISSUE THREAD

**Issue by certik** [TomHarte/CLK#776]
I built `clksignal` on Linux, downloaded `apple2o.rom` and `apple2-character.rom` and put them into `ROMImages/AppleII/` and run it with:
```
OSBindings/SDL/clksignal --disk-controller=None --model=II --output=CompositeColour --new=AppleII --rompath=`pwd`/ROMImages/
```
and a green window pops up. So I assume things work.

I have downloaded a disk image as a `.dsk` file. How do I load it? I couldn't figure it out.

Once I understand it, I am happy to submit a PR with documentation how to do it.

**Comment by TomHarte** [comment]
I can't immediately think of an issue that would cause a green window, so that's concerning. What you should see is a normal II boot, i.e. a screen full of random characters and a monitor prompt at the bottom.

Otherwise, if you have a dsk you want to load then you can skip all the other options and just use `OSBindings/SDL/clksignal file.dsk --rompath=`pwd`/ROMImages/, though that defaults to a IIe because it's more user-friendly so you can add `--model=II` to override that. Since it'll need to emulate a Disk II it'll need additional ROM images for that device but it should give you the relevant details. Apologies for being a little oblique there; I'm on my work computer but will return with greater specifics later.

If you had started with `--dsk-controller=sixteensector` then you could drag and drop the dsk over a running machine to insert it.

**Comment by certik** [comment]
@TomHarte thanks for the reply. I wonder if I downloaded incorrect `apple2o.rom` images. I understand that one cannot distribute such images for legal reasons. Would it make sense to include sha256 sums of the expected images, so that new users like myself can easily check if we downloaded the correct ones?

**Comment by xandark** [comment]
I was also getting green screens on my Linux-compiled version of Clock Signal until just now :)

**Comment by TomHarte** [comment]
I guess that since Linux can now alternatively mean the Qt build — in March it always meant SDL, that's no longer true — additional instructions for that, though they're very similar:

Option (1): configure a suitable Apple II, with a disk controller, from the launch UI, then use File -> Insert... or drag and drop the disk image onto the Apple II.

Option (2): don't configure a machine at all; use File -> Open... to select a disk image, and let the emulator pick and start a suitable Apple II, which will then boot from the inserted disk.
