### ISSUE TITLE
IRC or Discord channel?

### ISSUE THREAD

**Issue by qeeg** [TomHarte/CLK#784]
I'd really like to potentially contribute to this emulator, but I have nowhere to instantly communicate with you about this emulator... Maybe you could create an IRC or Discord channel?

**Comment by TomHarte** [comment]
Sure; I've never bothered with anything like that in the past because I don't think I even really have any users, never mind anything else, but I've set up a quick Discord channel as 'Clock Signal' — https://discord.gg/ZKkA3M 

I'm lucky enough still to be full-time employed, in the EST time zone, but I'll check in outside of those hours.
