### ISSUE TITLE
Compiling failure on Linux Mint

### ISSUE THREAD

**Issue by Jamirus238** [TomHarte/CLK#795]
I don't have much experience with Linux and compiling, so pardon me if this might be just a trivial fix.

I tried to compile the emulator on Linux Mint 18.3, it terminates after errors. I've pasted the output here:
https://pastebin.com/SrF39zFZ

**Comment by TomHarte** [comment]
I fixed as many issues as I immediately understand from the provided paste, so thanks for that. 

Some of the others don't immediately make sense to me, e.g. [gcd definitely is a member of the std namespace as of C++17](https://en.cppreference.com/w/cpp/numeric/gcd) (and Storage.hpp includes <numeric>) so I plan to install Linux Mint 18.3 over the weekend and take a closer look at it.

**Comment by TomHarte** [comment]
I overlapped it with cooking and installed today.

The issue is that Linux Mint is that it ships with GCC 5, and even after an `apt-get update` appears to list nothing newer than GCC 6. [GCC 7 was the first version fully to support C++17](https://gcc.gnu.org/projects/cxx-status.html#cxx17), including e.g. `if constexpr`.

Since Mate 18.3 is fully supported until 2021 I think I should try to find a way to support older versions of GCC. On the plus side, now that I know what the problem is it should be pretty easy to add an automated test.

I'll start looking at it in the near future.

**Comment by Jamirus238** [comment]
Thanks for being so quick! I've looked around, installed a bunch of stuff, this
https://gist.github.com/youmych/122e32cfa1c228c84684fec13b7d52e1
worked, afterwards GCC 7 was listed as the default and CLK compiled. Managed to launch Amstrad CPC so it seems to work, I'll fiddle around and maybe provide some additional feedback later.

**Comment by ryandesign** [comment]
Meanwhile it's the end of 2023, Linux Mint 18 has been EOL for years, and Linux Mint 20 and 21 are available. Do they have newer compilers that can compile Clock Signal OK? If so, maybe this issue can just be closed.

**Comment by TomHarte** [comment]
I'll assume this can be closed.

I'm still sheepish about adopting C++20 though, such as it's relevant.

**Comment by ryandesign** [comment]
I installed Linux Mint 21.2. It came with gcc 11 installed. I installed g++ 11 to match and it compiled Clock Signal just fine.
