### ISSUE TITLE
Frogger (Mac) hangs after presing "Play"

### ISSUE THREAD

**Issue by sy2002** [TomHarte/CLK#801]
Reproduction (using a macOS 10.14)

1. Use this Frogger disk: [Frogger.zip](https://github.com/TomHarte/CLK/files/4769863/Frogger.zip)
2. Wait until CLK shows the start screen
3. Press the play button

Problem: Does not continue from here

I made a small video that shows the reproduction steps (due to "wesendit" restrictions, only available for 7 days from today on): https://wsi.li/dl/uNMMJ8EYhzcbN3s3s/

For ensuring that the disk image itself is correct, I showed in the video reproduction that it works with "Mini vMac"

P.S. Awesome job! I love CLK.

**Comment by TomHarte** [comment]
I had a quick look in case it was something easy, but I suspect it might be an IWM emulation issue. Superficial observations: the game keeps the disk spinning on track 11 and spends a lot of time polling IWM status. It seems to do this while the menu is displayed, and then when play is pressed starts doing only that. Possibly it's waiting for some sort of event that for some reason I'm not delivering?

It's also possible I'm mishandling the IMG file format somehow and mistranscoding track 11, but I think that's less likely since the linked image is fairly simple.

**Comment by sy2002** [comment]
Thank you for this feedback, Tom.

**Comment by sy2002** [comment]
Hi Tom, in your recent release note you wrote:

> adds support for most WOZ 2-format disk images for the Apple II, fixing some latent issues around booting 13-sector disks and improving the Disk II static analyser.


Is this related to this bug? If yes, I would retest.

**Comment by TomHarte** [comment]
No, actually I think the emulator might have regressed now that I'm giving it a quick midday test.

I'll confirm or deny and, if necessary, seek to fix this evening.

**Comment by TomHarte** [comment]
Regression dealt with, but to confirm: no visible progress on the main problem.

**Comment by sy2002** [comment]
Thank you for the feedback.

**Comment by sy2002** [comment]
@TomHarte I just read in your recent release notes:

"adds support for Macintosh drive images, in addition to its existing support for volume images"

Is this related to this issue here (so does it make sense for me to start re-testing some old disk images)?

**Comment by TomHarte** [comment]
Alas no; that's more related to hard-disk images: previous versions was aware only of vMac-esque volume images, where the file on your disk is a copy of the HFS or MFS volume only. The new version can still deal with those but it can also open Basilisk-style drive images, which include the partition map, the driver partition, plus arbitrarily many further volumes.

So it's more about the slow creep towards emulating newer versions of Mac OS. Nowadays the emulator also has a full PowerPC decoder but it can't yet actually execute PowerPC code.

I was hoping my foray into the Apple IIgs would give me the sort of breadth of test cases to really push both the IWM and the SCC, one of which is bound to be the problem here. But although it led to IWM improvements I'm still not really far enough along to have properly attacked the SCC.

**Comment by sy2002** [comment]
Thank you Tom, for your detailed answer.

**Comment by TomHarte** [comment]
That all being said, I think it's quite possible this issue has been resolved — even if unwittingly.
![Clock Signal Screen Shot 21-06-2021, 23 21 26 GMT-4](https://user-images.githubusercontent.com/1162152/122858095-adcb6b00-d2e7-11eb-82d6-ddd67d9e9543.png)

**Comment by sy2002** [comment]
COOL :-) Thank you!
