### ISSUE TITLE
Apple M1: Faulty video?

### ISSUE THREAD

**Issue by MaddTheSane** [TomHarte/CLK#857]
It looks like Clock Signal is having issues when run on Apple Silicon:

<img width="712" alt="Screen Shot 2020-12-05 at 9 56 35 PM" src="https://user-images.githubusercontent.com/719492/101272391-015dd900-3749-11eb-9113-56c77de1a307.png">
<img width="712" alt="Screen Shot 2020-12-05 at 10 20 02 PM" src="https://user-images.githubusercontent.com/719492/101272396-03279c80-3749-11eb-82e9-76eb031a1d01.png">

These are present if run under Rosetta 2 or run natively.
I have only tested Atari 2600 games.

**Comment by TomHarte** [comment]
Oh, looks like Yars' Revenge has seen a regression to a much earlier bug where the sprites constantly move left to right? That's at least not M1 related.

In both cases the vertical banding is something as-yet unknown. Likely some sort of latent Metal misuse if it shows up with or without Rosetta? I don't know offhand.

Alas, the earliest I will have an M1 Mac of my own is this Thursday, and I'm travelling for just more than two weeks from Saturday so I may not get to look at this properly until virtually January. But it's a bug, so it's immediately top of the list.

**Comment by TomHarte** [comment]
Notes on this, at long last: it seems to affect luminance+phase machines only (i.e. the Vic-20 and Atari 2600), but is independent of NTSC vs PAL. There seems to be some element of phase dependence and the effect persists regardless of output mode, suggesting it's something to do with the input.

**Comment by TomHarte** [comment]
So there seems to be some sort of disparity between the colour phase tagged to scans (i.e. runs of PCM output data) and those recorded at line ends, and I think this is causing the phase+luminance encoder improperly to encode composite video.

Specific clues:
* the Metal encoder for phase+luminance uses the scan values but the decoder uses the line values, suggesting a disparity; and
* output of e.g. the Apple II, which doesn't use an encoder at all, is displayed correctly, suggesting that the line values are probably correct.

That's subject to the specific relative frequencies of the Atari and the Vic-20 not happening to create a problem that the Apple II by luck avoids, of course.

A lucky side effect of the separate Metal and OpenGL backends is that the target for phase information is provided via dependency injection. So the proper path forward here is formal CRT unit testing, I think. That wasn't a realistic option when I first wrote the thing because it was welded much more directly to OpenGL.

**Comment by TomHarte** [comment]
Screenshot for later self below; it's the raw composite feed from an emulated Vic-20. Note the obvious phase discrepancies in the left border on the first pixel line. Though the right border looks fine, so there's obviously some nuance here.

![Screenshot 2021-05-03 at 18 02 45](https://user-images.githubusercontent.com/1162152/117597258-34026800-b113-11eb-8da5-497df101ce50.png)

**Comment by TomHarte** [comment]
Further notes to self on this:

The same issue is seen on a 2019 MacBook Pro, but remains absent on my previous development machine — the 2015 Retina MacBook.

So a random guess might be just that I've underspecified precision for my phase? It's currently a `half`, which has only 10 bits of mantissa so it would indeed get spotty over on the right-hand side of the display. As a relevant data point I should try upping `SourceInterpolator::unitColourPhase` and `::colourPhase` to full floats and see what difference that makes.

**Comment by TomHarte** [comment]
It was a two-line test, so I've taken a 15-minute work break to verify. That does indeed seem to have been the problem. Before and after pictures attached; will test this evening with a wider array of software.
![After](https://user-images.githubusercontent.com/1162152/128765700-2aaec39f-528f-4f96-90aa-1175128acce6.png)
![Before](https://user-images.githubusercontent.com/1162152/128765701-7a5c35b5-12df-4bcb-8d06-96c5dd7ea787.png)
