### ISSUE TITLE
ZX81 Galaxians hangs at a blank screen on load

### ISSUE THREAD

**Issue by patters-syno** [TomHarte/CLK#874]
Great emulator. I have been trying various classic from the ZX81 software library, but I notice that Galaxians seems to hang. This is the version I have tried: http://www.zx81stuff.org.uk/zx81/tape/Galaxians

**Comment by TomHarte** [comment]
Confirmed reproducible; results were:
* the TZX version always gives the intro screen very briefly before clearing the screen; and
* the .P version acts like the TZX version if the emulator's automatic tape motor control is disabled. Otherwise it skips the title screen and transitions directly to the permanent blank screen.
Will search further.

**Comment by TomHarte** [comment]
Well, I stupidly pushed straight to master, but I believe this was fixed by https://github.com/TomHarte/CLK/commit/f05260b839d226a8f11a682a965e8a4b1ef8f460

Underlying issue was:

The proper logic for the Z80's wait line is (NMI enabled) and [other things].

This emulator was failing to reset the wait line if software managed to disable NMI while the WAIT line was active. Which can just happen if the instruction that's supposed to disable the WAIT line just managed to slip through that closing gate — WAIT went active during the instruction, but not quite soon enough to pause that instruction.

Fixed [for the next release].

<img width="1105" alt="Screenshot 2021-03-06 at 22 04 21" src="https://user-images.githubusercontent.com/1162152/110227601-0822f600-7ec8-11eb-9faf-109288d4b981.png">
