### ISSUE TITLE
colour.rom for Oric 1

### ISSUE THREAD

**Issue by LukeZBaker** [TomHarte/CLK#942]
Hello

I'm at a lost about colour.rom file for the Oric 1. I've not seen another emulator that requires this file.

I understand that you don't provide this rom as copyright is unclear. But I'm at a loss how to get the colour rom.

I do have an original Oric 1. Did you dump the ROM from original hardware? 

Is the file commonly known under a different filename?

Thanks

**Comment by TomHarte** [comment]
I obtained it from [this forum](https://forum.defence-force.org/viewtopic.php?f=8&t=2248&hilit=colour+rom&start=15), but it's probably a bit ridiculous that I currently require it — it benefits composite video mode only, and even then is currently temporarily unused. I think what I should do is make it an optional way to improve composite emulation, and no more than that.

I'll keep this ticket open as a reminder to do that.

**Comment by LukeZBaker** [comment]
Thanks Tom!

With the file, everything is working except there's no audio. I see you already have an open issue for the Qt version.

I therefore tried to build the SDL version but have an issue with that, I'll raise that as a separate issue.

**Comment by TomHarte** [comment]
Oh! Then potentially-diagnostic follow-up on that: did you build for yourself with Qt, or install via the Snap? I'm starting to wonder whether the issue is just package management; the Qt audio output works fine when built for macOS and my code seems to be doing the proper thing of querying for supported audio rates, etc, not trying to impose any particular values that might not be supported on every platform.

**Comment by LukeZBaker** [comment]
I installed it via the Snap on Ubuntu 21.04.

**Comment by LukeZBaker** [comment]
You might be right thinking it's an issue with snap. Maybe a permissions problem?

I would try building the software myself with Qt, but I didn't find any instructions.
