### ISSUE TITLE
Apple II pixels not square

### ISSUE THREAD

**Issue by Tiza59** [TomHarte/CLK#945]
The display of a basic Apple 2 with the DOS 3.3 Master disk shows a screen that is condensed in the horizontal direction. As far as I remember the dots should be square on that display. I double-checked with Virtual II. Regards Uwe

**Comment by TomHarte** [comment]
To eliminate a potential implementation error first: on my computer an Apple II looks as attached. Is it showing with the same aspect ratio on yours?

<img width="712" alt="Screenshot 2021-05-31 at 18 09 37" src="https://user-images.githubusercontent.com/1162152/120245615-b1fdee80-c23b-11eb-8a39-e307c7ea3b4d.png">

**Comment by Tiza59** [comment]
Your screen shot is exactly what I get on my computer. If you open your screen shot in preview and use the magnifying glass on the checkerboard cursor you see it is not square. Please find enclosed a screen shoot of Virtual ][ with square pixels to illustrate the subtle difference.

<img width="666" alt="Bildschirmfoto 2021-06-01 um 09 48 41" src="https://user-images.githubusercontent.com/16560008/120286643-c7682c80-c2be-11eb-9abb-212ed4c601ac.png">

**Comment by TomHarte** [comment]
The aspect ratios that machines display at in general falls out mathematically rather than being something I set but there are further caveats here:

The Apple II specifies that it is connected to a display with regular NTSC timing. This may not be true. Of other machines that I'm familiar with, the BBC and Electron are examples of machines that produce almost square pixels on a plain television but which were commonly connected to monitors — and  it was not uncommon for the monitor to be calibrated such that pixels actually were square. Therefore an owner might accurately remember square pixels.

So I'm going to dig around for photos of original Apple II-in-use photographs and try to figure out how common that was with the Apple II. This possibly suggests an additional type of video output should be offered.

**Comment by TomHarte** [comment]
So this was the best flat-on picture I could find of a real, running Apple II: https://www.oldcomputr.com/wp-content/uploads/2015/12/apple_iie.jpg

Comparing that to this emulator, the image appears to be about 8% wider, which makes for very, very close to square pixels.

So: confirmed difference between the emulator and real hardware, will address.

**Comment by Tiza59** [comment]
Thank you Tom 

for fixing this on the Apple 2 and on the Mac where I didn't notice it. Luckily there is an exact description on video timing plus Vertical Blanking Intervals etc. on the early Macs in the Guide to the Macintosh Hardware Family 2nd edition, 1990. Page 399 has a good hint. https://www.apple.asimov.net/documentation/macintosh/Guide_to_the_Macintosh_Family_Hardware%20%28Second%20Edition%29.pdf
<img width="687" alt="Bildschirmfoto 2021-06-08 um 16 16 49" src="https://user-images.githubusercontent.com/16560008/121203562-7cc65180-c876-11eb-9bf9-7e4f4cd1b8d3.png">

**Comment by TomHarte** [comment]
Such as it might matter, I did indeed seem to learn that calibrating Apple II monitors for square pixels was likely inspired by the Macintosh and the emphasis Apple subsequently put on square pixels being a good thing.

Anyway, I'm going to make sure this new option is exposed in Qt, land the current pull request, and probably put out a binary this weekend. So if you want a signed build, it'll be available by then. I can also attach one here if it's easier.
