### ISSUE TITLE
macOS/ARM64: CLK builds x86_64-only libraries

### ISSUE THREAD

**Issue by kehak** [TomHarte/CLK#984]
On macOS, Clock Signal is compiled as a "fat" muti-arch binary, however, none of its dependencies are, so their code runs under x86_64 emulation. This may have a measurable performance and efficiency impact on ARM64.

```
~/bin/Clock Signal.app/Contents/MacOS% lipo -archs ./Clock\ Signal 
arm64 x86_64

~/bin/Clock Signal.app/Contents/Frameworks% for LIB in *; do echo $(lipo -archs $LIB) $LIB; done
x86_64 libswiftAppKit.dylib
x86_64 libswiftCloudKit.dylib
x86_64 libswiftContacts.dylib
x86_64 libswiftCore.dylib
x86_64 libswiftCoreAudio.dylib
x86_64 libswiftCoreData.dylib
x86_64 libswiftCoreFoundation.dylib
x86_64 libswiftCoreGraphics.dylib
x86_64 libswiftCoreImage.dylib
x86_64 libswiftCoreLocation.dylib
x86_64 libswiftDarwin.dylib
x86_64 libswiftDispatch.dylib
x86_64 libswiftFoundation.dylib
x86_64 libswiftIOKit.dylib
x86_64 libswiftMetal.dylib
x86_64 libswiftMetalKit.dylib
x86_64 libswiftModelIO.dylib
x86_64 libswiftObjectiveC.dylib
x86_64 libswiftQuartzCore.dylib
x86_64 libswiftXPC.dylib
x86_64 libswiftos.dylib
x86_64 libswiftsimd.dylib
```

I'm not yet familiar with the build process as I've recently migrated to macOS from Linux, but apparently the ARM64 target architecture must be missing from a Makefile.

By the way, I take this opportunity to thank you for Clock Signal. I was looking for something as convenient to use as Virtual ][ yet as accurate as MAME, without the inaccuracy of the first nor the bloat and awkwardness of the second. CLK even runs cycle-counting demos, as long as they don't require a Mockingbird (sound card). Thank you for this gem.

**Comment by TomHarte** [comment]
Thanks for your kind words! I really need to get around to finishing up my IIGS support sooner rather than later. Then I'll still have the IIc missing but that's a more minor omission. I think I'm also behind on WOZ file format support, there now being a third version of that. And I keep meaning to spend some proper time on the Mockingboard — I've both the AY and the 6522 already implemented for other systems, so I could do the non-speech versions relatively easily, with an emphasis on 'relatively'.

On the libswifts, I have the feeling they may be included by the compiler only for older versions of macOS and therefore just inherently support x86 only. If that's correct then the system-level Swift libraries should be used instead on M1 machines. But these are just things I have a vague sense of being true rather than anything I can currently prove so I'll check that out properly.

**Comment by kehak** [comment]
Your assumption was correct, CLK turns out to work fine with the Framework folder deleted, which means macOS uses its system-level ARM64 libraries. I also don't see any difference in CPU usage so I assume it used the proper libraries even with the Framework folder present.

I will close the issue for now. Thanks for your commitment to this project, I'm looking forward to see the Mockingboard support!
